spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clear_solutions"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    format:
      date: yyyy-MM-dd

min-age: "18"